
-- Create objects bucket for conversation assets
INSERT INTO storage.buckets (id, name)
VALUES ('conversations', 'conversations')
ON CONFLICT (id) DO NOTHING;

-- Storage Access Control Policies (RLS)

-- Only participants can read the conversation message assets
CREATE POLICY "Active Participants can READ all conversation message assets"
  ON storage.objects
  FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'conversations'
    AND
    private.check_user_is_active_conversation_participant(
      ((storage.foldername(name))[1])::uuid, -- conversation id
      (SELECT auth.uid())
    )
  );

-- Only active participants can INSERT assets to non-existing messages they will create the message-id for in the client.
CREATE POLICY "Active Participants can INSERT assets to non-existing messages that they will create soon"
  ON storage.objects
  FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'conversations'
    AND
    -- Make sure the author is still active in the conversation
    private.check_user_is_active_conversation_participant(
      ((storage.foldername(name))[1])::uuid, -- conversation id
      (SELECT auth.uid())
    )
    AND
    (
      -- Make sure the message-id generated by the client does not exist yet
      private.check_message_not_exists(((storage.foldername(name))[2])::uuid)
      OR
      -- Or, if the message-id exists, make sure user is message author and still active
      private.check_is_active_message_author(
        ((storage.foldername(name))[2])::uuid, -- client generated message id
        (SELECT auth.uid())
      )
    )
  );

-- Only message authors can UPDATE the conversation message assets
CREATE POLICY "Active Message Authors can UPDATE assets (not their ownership)"
  ON storage.objects
  FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'conversations'
    AND
    private.check_is_active_message_author(
      ((storage.foldername(name))[2])::uuid, -- message id
      (SELECT auth.uid())
    )
  )
  -- Make sure the author can't change ownership of the asset
  WITH CHECK (
    bucket_id = 'conversations'
    AND
    private.check_is_active_message_author(
      ((storage.foldername(name))[2])::uuid, -- message id
      (SELECT auth.uid())
    )
  );

-- Only active message authors can DELETE the conversation message assets
CREATE POLICY "Active Message authors can DELETE their assets"
  ON storage.objects
  FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'conversations'
    AND
    private.check_is_active_message_author(
      ((storage.foldername(name))[2])::uuid, -- message id
      (SELECT auth.uid())
    )
  );

-- Conversation owners can delete all conversation message assets
CREATE POLICY "Conversation Owners can DELETE all conversation message assets"
  ON storage.objects
  FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'conversations'
    AND
    private.check_user_is_conversation_owner(
      ((storage.foldername(name))[1])::uuid, -- conversation id
      (SELECT auth.uid())
    )
  );
