/**
 * Environment variable name constants.
 * Use these constants instead of hardcoding env var names to ensure consistency
 * across edge functions, config, and documentation.
 */

// API Keys
export const ENV_VAR_OPENWEATHER_API_KEY = 'OPENWEATHER_API_KEY';
export const ENV_VAR_FINNHUB_API_KEY = 'FINNHUB_API_KEY';
export const ENV_VAR_ELEVENLABS_API_KEY = 'ELEVENLABS_API_KEY';
export const ENV_VAR_OPENAI_API_KEY = 'OPENAI_API_KEY';
export const ENV_VAR_GEMINI_API_KEY = 'GEMINI_API_KEY';
export const ENV_VAR_GROK_API_KEY = 'GROK_API_KEY';
export const ENV_VAR_RESEND_API_KEY = 'RESEND_API_KEY';
export const ENV_VAR_GOOGLE_MAPS_API_KEY = 'GOOGLE_MAPS_API_KEY';
export const ENV_VAR_MAPBOX_ACCESS_TOKEN = 'MAPBOX_ACCESS_TOKEN';
export const ENV_VAR_GOOGLE_VERTEX_API_KEY = 'GOOGLE_VERTEX_API_KEY';
export const ENV_VAR_GOOGLE_CLOUD_PROJECT_ID = 'GOOGLE_CLOUD_PROJECT_ID';

// Frontend analytics config
export const ENV_VAR_EXPO_PUBLIC_POSTHOG_PROJECT_TOKEN = 'EXPO_PUBLIC_POSTHOG_PROJECT_TOKEN';
export const ENV_VAR_EXPO_PUBLIC_POSTHOG_PROJECT_ID = 'EXPO_PUBLIC_POSTHOG_PROJECT_ID';
export const ENV_VAR_EXPO_PUBLIC_POSTHOG_PROJECT_REGION = 'EXPO_PUBLIC_POSTHOG_PROJECT_REGION';
export const ENV_VAR_EXPO_PUBLIC_POSTHOG_ENABLED = 'EXPO_PUBLIC_POSTHOG_ENABLED';
